### ISSUE TITLE
states.activity_manager does not work any longer

### ISSUE THREAD

**Issue by aerozinga** [pathofleastresistor/activity-manager#8] opened 2023-12-18 21:03 UTC
Hi,

I love your activity manager and use it daily. I just found that this code does not seem to work any longer since your latest updated
```
    {%- for activity in states.activity_manager -%}
    {%- if activity.state|as_datetime < now() and activity.attributes.category=="Workout"  -%}
    {{ new_line() }}{{ " - "}}{{  activity.name }}
    {%- endif -%}
    {%- endfor %}
```

My current work around to count the number of activities overdue is currently like this: (somehow states.activity_manager does not give any results any longer and activities are now having entity_ids like "sensor.category_activity_name" instead.

```
{% set Count = namespace(value=0) %}
{%- for activity in states.sensor if 'sensor.home_' in activity.entity_id and not 'home_assistant_' in activity.entity_id and activity.state|as_datetime < now() %}
{% set Count.value = Count.value + 1 %}
{% endfor -%}
{{ Count.value }}
```

**Comment by pathofleastresistor** [comment] 2023-12-19 03:20
Really appreciate you finding this component useful! Can you confirm the latest version you're on? If you're on 0.0.5-beta I would recommend rolling back to 0.0.4 for now.

I realized that the move to sensor does break the ability to count and I don't have an answer to that yet. I do think I need to solve that before launching 0.0.5.

If you're on 0.0.4, please let me know. Because then that's a bug in that release :/.

**Comment by aerozinga** [comment] 2023-12-21 13:44
Ah alright, I am on 0.0.5-beta That's why. Ok, then you can close the issue and I am waiting for the magic to come :)

**Comment by pathofleastresistor** [comment] 2023-12-22 23:20
Duplicate of #9

**Closed by pathofleastresistor** 2023-12-22 23:20 UTC
